user crud
wolox-training/or-java pull request #3
Opened 2020-07-03 18:31 UTC by oarozu

Crear User controller con las operaciones CRUD de User

https://trello.com/c/BuaB2yAe/21-crear-user-controller-con-las-operaciones-crud-de-user

2020-07-03 18:42 UTC, cramallo requested changes

2020-07-03 18:42 UTC, cramallo commented on src/main/java/wolox/training/controllers/UserController.java
> +    private BookService bookRepository;
remove the repository from here, you should use the repository in the service

2020-07-03 18:42 UTC, cramallo commented on src/main/java/wolox/training/controllers/UserController.java
> +        User user = userService.findById(user_id);
You can do all this in the service

2020-07-03 18:42 UTC, cramallo commented on src/main/java/wolox/training/services/UserService.java
> +public class UserService {
use @Service annotation

2020-07-03 18:43 UTC, cramallo reviewed
Remember the uses of "final" in variables that won't never change

2020-07-06 14:00 UTC, cramallo commented on src/main/java/wolox/training/controllers/UserController.java
> +    private BookService bookService;
you never use this service here, you should remove this

2020-07-06 20:29 UTC, cramallo approved these changes

2020-07-07 14:18 UTC, facucompe approved these changes

2020-07-07 20:52 UTC, merged